---
- name: Install Prometheus Node Exporter
  hosts: all
  become: yes
  vars:
    node_exporter_version: "1.3.1"  # Specify default version, can be overridden
    node_exporter_user: prometheus
    node_exporter_group: prometheus

  tasks:
    - name: Create prometheus group
      group:
        name: "{{ node_exporter_group }}"
        state: present

    - name: Create user for Node Exporter
      user:
        name: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"
        system: yes
        createhome: no

    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        mode: '0664'

    - name: Extract Node Exporter
      unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/opt"
        remote_src: yes
        creates: "/opt/node_exporter-{{ node_exporter_version }}.linux-amd64"

    - name: Copy node_exporter binary to /usr/local/bin
      copy:
        src: "/opt/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"
        mode: '0755'

    - name: Deploy systemd service file for Node Exporter
      template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
      notify:
        - reload systemd
        - restart node_exporter

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart node_exporter
      systemd:
        name: node_exporter
        state: restarted
        enabled: yes
